# Generated by Django 5.1.6 on 2025-04-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Title', max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('release_date', models.DateTimeField()),
                ('picture', models.ImageField(default='No Image', upload_to='')),
            ],
        ),
    ]
