# Generated by Django 5.1.6 on 2025-04-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='release_date',
        ),
    ]
